name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  changed-files:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    outputs:
      go-files: ${{ steps.go-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Check for relevant go file changes (or related)
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        id: go-files
        with:
          # Any Go code or files that directly relate to testing Go code (like this one)
          files: |
            **/*.go
            go.mod
            .golangci.yml
            .github/workflows/ci.yml

  ci:
    if: ${{ needs.changed-files.outputs.go-files == 'true' || github.event_name != 'pull_request' }}
    needs: changed-files
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
          cache: true

      - name: vet
        run: go vet ./...

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: test
        run: go test -vet=off -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1

      - name: coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.out
